#!/usr/bin/env python3
"""Every engagement number quoted on the "defining active" and power-user-curve pages.

Internal build script. Not linked from any audience-facing page.

Usage
-----
  python3 materials/engagement-numbers.py <cache-dir> [--write-js]

Reads <cache-dir>/actor-days.json from fetch-gharchive-actors.py: two sampled hours a day
(03:00 and 15:00 UTC) for 28 days, 2024-03-04 to 2024-03-31, every account whose id is
divisible by 20. Accounts whose login ends in "[bot]" are dropped here and the count is printed.

An account is "active on a day" under a definition if, in either sampled hour of that UTC day,
it did the thing:  any = any event, push = a PushEvent, open = opened an issue or pull request.
--write-js writes assets/pa-engagement.js (the L28 histograms, json.dumps) for the page figures.
"""
import json
import os
import re
import sys
from collections import defaultdict

DEFS = {"any": lambda v: v[1] > 0, "push": lambda v: v[2] > 0, "open": lambda v: v[3] > 0}


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    hours = json.load(open(os.path.join(sys.argv[1], "actor-days.json")))
    days = sorted({h.rsplit("-", 1)[0] for h in hours})
    assert len(days) == 28, len(days)
    bots, seen = set(), defaultdict(lambda: {d: set() for d in DEFS})
    logins, events = {}, defaultdict(int)
    for h, blob in hours.items():
        day = h.rsplit("-", 1)[0]
        for aid, v in blob["actors"].items():
            if v[0].endswith("[bot]"):
                bots.add(aid)
                continue
            logins[aid] = v[0]
            events[aid] += v[1]
            for d, test in DEFS.items():
                if test(v):
                    seen[aid][d].add(day)
    print("sampled accounts seen at least once:", len(seen), " bot accounts dropped:", len(bots))
    ev = sorted(events.values(), reverse=True)
    print("top 1 percent of accounts by events hold %.1f%% of all sampled events" % (100 * sum(ev[: len(ev) // 100]) / sum(ev)))
    out = {}
    for d in DEFS:
        ldays = [len(s[d]) for s in seen.values() if s[d]]
        mau = len(ldays)
        dau = [sum(1 for s in seen.values() if day in s[d]) for day in days]
        avg_dau = sum(dau) / 28
        hist = [0] * 29
        for x in ldays:
            hist[x] += 1
        wk = [sum(1 for s in seen.values() if any(day in s[d] for day in days[i:i + 7])) for i in (0, 7, 14, 21)]
        print("\n[%s] MAU (active on >= 1 of 28 days): %d" % (d, mau))
        print("  average DAU %.1f  stickiness DAU/MAU %.1f%%  average WAU %.1f  DAU/WAU %.1f%%" % (
            avg_dau, 100 * avg_dau / mau, sum(wk) / 4, 100 * avg_dau / (sum(wk) / 4)))
        print("  L28 share on 1 day %.1f%%, 2-3 days %.1f%%, 4-7 %.1f%%, 8-14 %.1f%%, 15-21 %.1f%%, 22-28 %.1f%%" % tuple(
            100 * sum(hist[a:b + 1]) / mau for a, b in ((1, 1), (2, 3), (4, 7), (8, 14), (15, 21), (22, 28))))
        print("  active all 28 days: %d (%.2f%%); median days %d" % (hist[28], 100 * hist[28] / mau, sorted(ldays)[mau // 2]))
        top = sorted(ldays, reverse=True)[: max(1, mau // 10)]
        print("  top 10%% of accounts by days hold %.1f%% of account-days" % (100 * sum(top) / sum(ldays)))
        tail = [a for a, sd in seen.items() if len(sd[d]) >= 22]
        botish = [a for a in tail if re.search(r"bot|-ci\b|ci-|sync|deploy|commenter|assistant", logins[a], re.I)]
        print("  accounts on 22+ days: %d, of which %d have bot-like names without the [bot] suffix" % (len(tail), len(botish)))
        out[d] = {"mau": mau, "avgDau": round(avg_dau, 1), "hist": hist}
    if "--write-js" in sys.argv:
        here = os.path.dirname(os.path.abspath(__file__))
        with open(os.path.join(here, "..", "assets", "pa-engagement.js"), "w") as f:
            f.write("/* pa-engagement.js - L28 histograms from GH Archive, 5 percent account sample, March 2024.\n"
                    " * Generated by materials/engagement-numbers.py with json.dumps. */\n"
                    "window.PA_ENGAGEMENT = " + json.dumps(out, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    main()
